package modele;
// Generated 24 sept. 2019 13:48:26 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Boutiquier generated by hbm2java
 */
@Entity
@Table(name = "boutiquier", schema = "public")
public class Boutiquier implements java.io.Serializable {

	private int idboutiquier;
	private Boutique boutique;
	private Integer nom;
	private Integer prenom;
	private Integer datenaiss;
	private Integer adresse;
	private Integer telephone;
	private Integer email;
	private Integer motpass;
	private Set comptevirtuels = new HashSet(0);
	private Set comptes = new HashSet(0);

	public Boutiquier() {
	}

	public Boutiquier(int idboutiquier) {
		this.idboutiquier = idboutiquier;
	}

	public Boutiquier(int idboutiquier, Boutique boutique, Integer nom, Integer prenom, Integer datenaiss,
			Integer adresse, Integer telephone, Integer email, Integer motpass, Set comptevirtuels, Set comptes) {
		this.idboutiquier = idboutiquier;
		this.boutique = boutique;
		this.nom = nom;
		this.prenom = prenom;
		this.datenaiss = datenaiss;
		this.adresse = adresse;
		this.telephone = telephone;
		this.email = email;
		this.motpass = motpass;
		this.comptevirtuels = comptevirtuels;
		this.comptes = comptes;
	}

	@Id

	@Column(name = "idboutiquier", unique = true, nullable = false)
	public int getIdboutiquier() {
		return this.idboutiquier;
	}

	public void setIdboutiquier(int idboutiquier) {
		this.idboutiquier = idboutiquier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idboutique")
	public Boutique getBoutique() {
		return this.boutique;
	}

	public void setBoutique(Boutique boutique) {
		this.boutique = boutique;
	}

	@Column(name = "nom")
	public Integer getNom() {
		return this.nom;
	}

	public void setNom(Integer nom) {
		this.nom = nom;
	}

	@Column(name = "prenom")
	public Integer getPrenom() {
		return this.prenom;
	}

	public void setPrenom(Integer prenom) {
		this.prenom = prenom;
	}

	@Column(name = "datenaiss")
	public Integer getDatenaiss() {
		return this.datenaiss;
	}

	public void setDatenaiss(Integer datenaiss) {
		this.datenaiss = datenaiss;
	}

	@Column(name = "adresse")
	public Integer getAdresse() {
		return this.adresse;
	}

	public void setAdresse(Integer adresse) {
		this.adresse = adresse;
	}

	@Column(name = "telephone")
	public Integer getTelephone() {
		return this.telephone;
	}

	public void setTelephone(Integer telephone) {
		this.telephone = telephone;
	}

	@Column(name = "email")
	public Integer getEmail() {
		return this.email;
	}

	public void setEmail(Integer email) {
		this.email = email;
	}

	@Column(name = "motpass")
	public Integer getMotpass() {
		return this.motpass;
	}

	public void setMotpass(Integer motpass) {
		this.motpass = motpass;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boutiquier")
	public Set getComptevirtuels() {
		return this.comptevirtuels;
	}

	public void setComptevirtuels(Set comptevirtuels) {
		this.comptevirtuels = comptevirtuels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boutiquier")
	public Set getComptes() {
		return this.comptes;
	}

	public void setComptes(Set comptes) {
		this.comptes = comptes;
	}

}
