package modele;
// Generated 24 sept. 2019 13:48:26 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Boutique generated by hbm2java
 */
@Entity
@Table(name = "boutique", schema = "public")
public class Boutique implements java.io.Serializable {

	private int idboutique;
	private Quartier quartier;
	private Commercant commercant;
	private String nom;
	private Set produitts = new HashSet(0);
	private Set boutiquiers = new HashSet(0);

	public Boutique() {
	}

	public Boutique(int idboutique, Quartier quartier) {
		this.idboutique = idboutique;
		this.quartier = quartier;
	}

	public Boutique(int idboutique, Quartier quartier, Commercant commercant, String nom, Set produitts,
			Set boutiquiers) {
		this.idboutique = idboutique;
		this.quartier = quartier;
		this.commercant = commercant;
		this.nom = nom;
		this.produitts = produitts;
		this.boutiquiers = boutiquiers;
	}

	@Id

	@Column(name = "idboutique", unique = true, nullable = false)
	public int getIdboutique() {
		return this.idboutique;
	}

	public void setIdboutique(int idboutique) {
		this.idboutique = idboutique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idquartier", nullable = false)
	public Quartier getQuartier() {
		return this.quartier;
	}

	public void setQuartier(Quartier quartier) {
		this.quartier = quartier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcommercant")
	public Commercant getCommercant() {
		return this.commercant;
	}

	public void setCommercant(Commercant commercant) {
		this.commercant = commercant;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boutique")
	public Set getProduitts() {
		return this.produitts;
	}

	public void setProduitts(Set produitts) {
		this.produitts = produitts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boutique")
	public Set getBoutiquiers() {
		return this.boutiquiers;
	}

	public void setBoutiquiers(Set boutiquiers) {
		this.boutiquiers = boutiquiers;
	}

}
