package modele;
// Generated 24 sept. 2019 13:48:26 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clientvirtuel generated by hbm2java
 */
@Entity
@Table(name = "clientvirtuel", schema = "public")
public class Clientvirtuel implements java.io.Serializable {

	private int idclientv;
	private Set commandes = new HashSet(0);
	private Set comptevirtuels = new HashSet(0);

	public Clientvirtuel() {
	}

	public Clientvirtuel(int idclientv) {
		this.idclientv = idclientv;
	}

	public Clientvirtuel(int idclientv, Set commandes, Set comptevirtuels) {
		this.idclientv = idclientv;
		this.commandes = commandes;
		this.comptevirtuels = comptevirtuels;
	}

	@Id

	@Column(name = "idclientv", unique = true, nullable = false)
	public int getIdclientv() {
		return this.idclientv;
	}

	public void setIdclientv(int idclientv) {
		this.idclientv = idclientv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientvirtuel")
	public Set getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set commandes) {
		this.commandes = commandes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientvirtuel")
	public Set getComptevirtuels() {
		return this.comptevirtuels;
	}

	public void setComptevirtuels(Set comptevirtuels) {
		this.comptevirtuels = comptevirtuels;
	}

}
