package modele;
// Generated 24 sept. 2019 13:48:26 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name = "compte", schema = "public")
public class Compte implements java.io.Serializable {

	private int numero;
	private Client client;
	private Boutiquier boutiquier;
	private Date datecreation;
	private Integer solde;

	public Compte() {
	}

	public Compte(int numero, Client client, Boutiquier boutiquier) {
		this.numero = numero;
		this.client = client;
		this.boutiquier = boutiquier;
	}

	public Compte(int numero, Client client, Boutiquier boutiquier, Date datecreation, Integer solde) {
		this.numero = numero;
		this.client = client;
		this.boutiquier = boutiquier;
		this.datecreation = datecreation;
		this.solde = solde;
	}

	@Id

	@Column(name = "numero", unique = true, nullable = false)
	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idclient", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idboutiquier", nullable = false)
	public Boutiquier getBoutiquier() {
		return this.boutiquier;
	}

	public void setBoutiquier(Boutiquier boutiquier) {
		this.boutiquier = boutiquier;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datecreation", length = 13)
	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

	@Column(name = "solde")
	public Integer getSolde() {
		return this.solde;
	}

	public void setSolde(Integer solde) {
		this.solde = solde;
	}

}
