package modele;
// Generated 24 sept. 2019 13:48:26 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Conditionnement generated by hbm2java
 */
@Entity
@Table(name = "conditionnement", schema = "public")
public class Conditionnement implements java.io.Serializable {

	private int idcondition;
	private Produitt produitt;
	private String description;

	public Conditionnement() {
	}

	public Conditionnement(int idcondition, Produitt produitt) {
		this.idcondition = idcondition;
		this.produitt = produitt;
	}

	public Conditionnement(int idcondition, Produitt produitt, String description) {
		this.idcondition = idcondition;
		this.produitt = produitt;
		this.description = description;
	}

	@Id

	@Column(name = "idcondition", unique = true, nullable = false)
	public int getIdcondition() {
		return this.idcondition;
	}

	public void setIdcondition(int idcondition) {
		this.idcondition = idcondition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproduct", nullable = false)
	public Produitt getProduitt() {
		return this.produitt;
	}

	public void setProduitt(Produitt produitt) {
		this.produitt = produitt;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
