package modele;
// Generated 24 sept. 2019 13:48:26 by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detailscommande generated by hbm2java
 */
@Entity
@Table(name = "detailscommande", schema = "public")
public class Detailscommande implements java.io.Serializable {

	private DetailscommandeId id;
	private Commande commande;
	private Produitt produitt;
	private Integer quantite;

	public Detailscommande() {
	}

	public Detailscommande(DetailscommandeId id, Commande commande, Produitt produitt) {
		this.id = id;
		this.commande = commande;
		this.produitt = produitt;
	}

	public Detailscommande(DetailscommandeId id, Commande commande, Produitt produitt, Integer quantite) {
		this.id = id;
		this.commande = commande;
		this.produitt = produitt;
		this.quantite = quantite;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idcommande", column = @Column(name = "idcommande", nullable = false)),
			@AttributeOverride(name = "idproduct", column = @Column(name = "idproduct", nullable = false)) })
	public DetailscommandeId getId() {
		return this.id;
	}

	public void setId(DetailscommandeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcommande", nullable = false, insertable = false, updatable = false)
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproduct", nullable = false, insertable = false, updatable = false)
	public Produitt getProduitt() {
		return this.produitt;
	}

	public void setProduitt(Produitt produitt) {
		this.produitt = produitt;
	}

	@Column(name = "quantite")
	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

}
