package modele;
// Generated 24 sept. 2019 13:48:26 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetailscommandeId generated by hbm2java
 */
@Embeddable
public class DetailscommandeId implements java.io.Serializable {

	private int idcommande;
	private int idproduct;

	public DetailscommandeId() {
	}

	public DetailscommandeId(int idcommande, int idproduct) {
		this.idcommande = idcommande;
		this.idproduct = idproduct;
	}

	@Column(name = "idcommande", nullable = false)
	public int getIdcommande() {
		return this.idcommande;
	}

	public void setIdcommande(int idcommande) {
		this.idcommande = idcommande;
	}

	@Column(name = "idproduct", nullable = false)
	public int getIdproduct() {
		return this.idproduct;
	}

	public void setIdproduct(int idproduct) {
		this.idproduct = idproduct;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailscommandeId))
			return false;
		DetailscommandeId castOther = (DetailscommandeId) other;

		return (this.getIdcommande() == castOther.getIdcommande()) && (this.getIdproduct() == castOther.getIdproduct());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcommande();
		result = 37 * result + this.getIdproduct();
		return result;
	}

}
