package modele;
// Generated 24 sept. 2019 13:48:26 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produitt generated by hbm2java
 */
@Entity
@Table(name = "produitt", schema = "public")
public class Produitt implements java.io.Serializable {

	private int idproduct;
	private Categorie categorie;
	private Boutique boutique;
	private Stock stock;
	private String nom;
	private Set conditionnements = new HashSet(0);
	private Set depenseses = new HashSet(0);
	private Set detailscommandes = new HashSet(0);
	private Set formats = new HashSet(0);

	public Produitt() {
	}

	public Produitt(int idproduct, Categorie categorie, Stock stock) {
		this.idproduct = idproduct;
		this.categorie = categorie;
		this.stock = stock;
	}

	public Produitt(int idproduct, Categorie categorie, Boutique boutique, Stock stock, String nom,
			Set conditionnements, Set depenseses, Set detailscommandes, Set formats) {
		this.idproduct = idproduct;
		this.categorie = categorie;
		this.boutique = boutique;
		this.stock = stock;
		this.nom = nom;
		this.conditionnements = conditionnements;
		this.depenseses = depenseses;
		this.detailscommandes = detailscommandes;
		this.formats = formats;
	}

	@Id

	@Column(name = "idproduct", unique = true, nullable = false)
	public int getIdproduct() {
		return this.idproduct;
	}

	public void setIdproduct(int idproduct) {
		this.idproduct = idproduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategorie", nullable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idboutique")
	public Boutique getBoutique() {
		return this.boutique;
	}

	public void setBoutique(Boutique boutique) {
		this.boutique = boutique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idstock", nullable = false)
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produitt")
	public Set getConditionnements() {
		return this.conditionnements;
	}

	public void setConditionnements(Set conditionnements) {
		this.conditionnements = conditionnements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produitt")
	public Set getDepenseses() {
		return this.depenseses;
	}

	public void setDepenseses(Set depenseses) {
		this.depenseses = depenseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produitt")
	public Set getDetailscommandes() {
		return this.detailscommandes;
	}

	public void setDetailscommandes(Set detailscommandes) {
		this.detailscommandes = detailscommandes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produitt")
	public Set getFormats() {
		return this.formats;
	}

	public void setFormats(Set formats) {
		this.formats = formats;
	}

}
