package modele;
// Generated 24 sept. 2019 13:48:26 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quartier generated by hbm2java
 */
@Entity
@Table(name = "quartier", schema = "public")
public class Quartier implements java.io.Serializable {

	private int idquartier;
	private Depatrtement depatrtement;
	private String nom;
	private Set boutiques = new HashSet(0);

	public Quartier() {
	}

	public Quartier(int idquartier, Depatrtement depatrtement) {
		this.idquartier = idquartier;
		this.depatrtement = depatrtement;
	}

	public Quartier(int idquartier, Depatrtement depatrtement, String nom, Set boutiques) {
		this.idquartier = idquartier;
		this.depatrtement = depatrtement;
		this.nom = nom;
		this.boutiques = boutiques;
	}

	@Id

	@Column(name = "idquartier", unique = true, nullable = false)
	public int getIdquartier() {
		return this.idquartier;
	}

	public void setIdquartier(int idquartier) {
		this.idquartier = idquartier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddepartement", nullable = false)
	public Depatrtement getDepatrtement() {
		return this.depatrtement;
	}

	public void setDepatrtement(Depatrtement depatrtement) {
		this.depatrtement = depatrtement;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quartier")
	public Set getBoutiques() {
		return this.boutiques;
	}

	public void setBoutiques(Set boutiques) {
		this.boutiques = boutiques;
	}

}
