package model;
// Generated 14 juil. 2019 13:23:45 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Boutique generated by hbm2java
 */
@Entity
@Table(name = "boutique", schema = "public")
public class Boutique implements java.io.Serializable {

	private int idboutique;
	private Quartier quartier;
	private String nom;
	private Set<Compte> comptes = new HashSet<Compte>(0);
	private Set<Comptevirtuel> comptevirtuels = new HashSet<Comptevirtuel>(0);

	public Boutique() {
	}

	public Boutique(int idboutique, Quartier quartier) {
		this.idboutique = idboutique;
		this.quartier = quartier;
	}

	public Boutique(int idboutique, Quartier quartier, String nom, Set<Compte> comptes,
			Set<Comptevirtuel> comptevirtuels) {
		this.idboutique = idboutique;
		this.quartier = quartier;
		this.nom = nom;
		this.comptes = comptes;
		this.comptevirtuels = comptevirtuels;
	}

	@Id

	@Column(name = "idboutique", unique = true, nullable = false)
	public int getIdboutique() {
		return this.idboutique;
	}

	public void setIdboutique(int idboutique) {
		this.idboutique = idboutique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idquartier", nullable = false)
	public Quartier getQuartier() {
		return this.quartier;
	}

	public void setQuartier(Quartier quartier) {
		this.quartier = quartier;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boutique")
	public Set<Compte> getComptes() {
		return this.comptes;
	}

	public void setComptes(Set<Compte> comptes) {
		this.comptes = comptes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boutique")
	public Set<Comptevirtuel> getComptevirtuels() {
		return this.comptevirtuels;
	}

	public void setComptevirtuels(Set<Comptevirtuel> comptevirtuels) {
		this.comptevirtuels = comptevirtuels;
	}

}
