package model;
// Generated 14 juil. 2019 13:23:45 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", schema = "public")
public class Client implements java.io.Serializable {

	private Integer idclient;
	private String nom;
	private String prenom;
	private Date datenaiss;
	private String adresse;
	private String telephone;
	private String email;
	private String motpass;
	private Set<Compte> comptes = new HashSet<Compte>(0);
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Client() {
	}

	public Client(int idclient) {
		this.idclient = idclient;
	}

	public Client(Integer idclient, String nom, String prenom, Date datenaiss, String adresse, String telephone,
			String email, String motpass, Set<Compte> comptes, Set<Commande> commandes) {
		this.idclient = idclient;
		this.nom = nom;
		this.prenom = prenom;
		this.datenaiss = datenaiss;
		this.adresse = adresse;
		this.telephone = telephone;
		this.email = email;
		this.motpass = motpass;
		this.comptes = comptes;
		this.commandes = commandes;
	}

	@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idclient", unique = true, nullable = false)
	public Integer getIdclient() {
		return this.idclient;
	}

	public void setIdclient(Integer idclient) {
		this.idclient = idclient;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datenaiss", length = 13)
	public Date getDatenaiss() {
		return this.datenaiss;
	}

	public void setDatenaiss(Date datenaiss) {
		this.datenaiss = datenaiss;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "telephone", length = 254)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "email", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "motpass", length = 254)
	public String getMotpass() {
		return this.motpass;
	}

	public void setMotpass(String motpass) {
		this.motpass = motpass;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client",cascade=CascadeType.ALL)
	public Set<Compte> getComptes() {
		return this.comptes;
	}

	public void setComptes(Set<Compte> comptes) {
		this.comptes = comptes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client",cascade=CascadeType.ALL)
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
