package model;
// Generated 14 juil. 2019 13:23:45 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", schema = "public")
public class Commande implements java.io.Serializable {

	private int idcommande;
	private Client client;
	private Facture facture;
	private Clientvirtuel clientvirtuel;
	private Date datecmd;
	private Set<Detailscommande> detailscommandes = new HashSet<Detailscommande>(0);
	private Set<Facture> factures = new HashSet<Facture>(0);

	public Commande() {
	}

	public Commande(int idcommande, Client client, Facture facture, Clientvirtuel clientvirtuel) {
		this.idcommande = idcommande;
		this.client = client;
		this.facture = facture;
		this.clientvirtuel = clientvirtuel;
	}

	public Commande(int idcommande, Client client, Facture facture, Clientvirtuel clientvirtuel, Date datecmd,
			Set<Detailscommande> detailscommandes, Set<Facture> factures) {
		this.idcommande = idcommande;
		this.client = client;
		this.facture = facture;
		this.clientvirtuel = clientvirtuel;
		this.datecmd = datecmd;
		this.detailscommandes = detailscommandes;
		this.factures = factures;
	}

	@Id

	@Column(name = "idcommande", unique = true, nullable = false)
	public int getIdcommande() {
		return this.idcommande;
	}

	public void setIdcommande(int idcommande) {
		this.idcommande = idcommande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idclient", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfacture", nullable = false)
	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idclientv", nullable = false)
	public Clientvirtuel getClientvirtuel() {
		return this.clientvirtuel;
	}

	public void setClientvirtuel(Clientvirtuel clientvirtuel) {
		this.clientvirtuel = clientvirtuel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datecmd", length = 13)
	public Date getDatecmd() {
		return this.datecmd;
	}

	public void setDatecmd(Date datecmd) {
		this.datecmd = datecmd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commande")
	public Set<Detailscommande> getDetailscommandes() {
		return this.detailscommandes;
	}

	public void setDetailscommandes(Set<Detailscommande> detailscommandes) {
		this.detailscommandes = detailscommandes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commande")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
