package model;
// Generated 14 juil. 2019 13:23:45 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commercant generated by hbm2java
 */
@Entity
@Table(name = "commercant", schema = "public")
public class Commercant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idcommercant;
	private String nom;
	private String prenom;
	private Date datenaiss;
	private String email;
	private String adresse;
	private String telephone;
	private String motpass;
	private Set<Depenses> depenseses = new HashSet<Depenses>(0);
	private Set<Boutiquier> boutiquiers = new HashSet<Boutiquier>(0);

	public Commercant() {
	}

	public Commercant(Integer idcommercant) {
		this.idcommercant = idcommercant;
	}

	public Commercant(Integer idcommercant, String nom, String prenom, Date datenaiss, String email, String adresse,
			String telephone, String motpass, Set<Depenses> depenseses, Set<Boutiquier> boutiquiers) {
		this.idcommercant = idcommercant;
		this.nom = nom;
		this.prenom = prenom;
		this.datenaiss = datenaiss;
		this.email = email;
		this.adresse = adresse;
		this.telephone = telephone;
		this.motpass = motpass;
		this.depenseses = depenseses;
		this.boutiquiers = boutiquiers;
	}

	@Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idcommercant", unique = true, nullable = false)
	public Integer getIdcommercant() {
		return this.idcommercant;
	}

	public void setIdcommercant(Integer idcommercant) {
		this.idcommercant = idcommercant;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datenaiss", length = 13)
	public Date getDatenaiss() {
		return this.datenaiss;
	}

	public void setDatenaiss(Date datenaiss) {
		this.datenaiss = datenaiss;
	}

	@Column(name = "email", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "telephone", length = 254)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "motpass", length = 254)
	public String getMotpass() {
		return this.motpass;
	}

	public void setMotpass(String motpass) {
		this.motpass = motpass;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commercant",cascade=CascadeType.ALL)
	public Set<Depenses> getDepenseses() {
		return this.depenseses;
	}

	public void setDepenseses(Set<Depenses> depenseses) {
		this.depenseses = depenseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commercant" ,cascade=CascadeType.ALL)
	public Set<Boutiquier> getBoutiquiers() {
		return this.boutiquiers;
	}

	public void setBoutiquiers(Set<Boutiquier> boutiquiers) {
		this.boutiquiers = boutiquiers;
	}

}
