package model;
// Generated 14 juil. 2019 13:23:45 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comptevirtuel generated by hbm2java
 */
@Entity
@Table(name = "comptevirtuel", schema = "public")
public class Comptevirtuel implements java.io.Serializable {

	private int idcomptev;
	private Boutique boutique;
	private Boutiquier boutiquier;
	private Clientvirtuel clientvirtuel;
	private Date datecmp;

	public Comptevirtuel() {
	}

	public Comptevirtuel(int idcomptev, Boutique boutique, Boutiquier boutiquier, Clientvirtuel clientvirtuel) {
		this.idcomptev = idcomptev;
		this.boutique = boutique;
		this.boutiquier = boutiquier;
		this.clientvirtuel = clientvirtuel;
	}

	public Comptevirtuel(int idcomptev, Boutique boutique, Boutiquier boutiquier, Clientvirtuel clientvirtuel,
			Date datecmp) {
		this.idcomptev = idcomptev;
		this.boutique = boutique;
		this.boutiquier = boutiquier;
		this.clientvirtuel = clientvirtuel;
		this.datecmp = datecmp;
	}

	@Id

	@Column(name = "idcomptev", unique = true, nullable = false)
	public int getIdcomptev() {
		return this.idcomptev;
	}

	public void setIdcomptev(int idcomptev) {
		this.idcomptev = idcomptev;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idboutique", nullable = false)
	public Boutique getBoutique() {
		return this.boutique;
	}

	public void setBoutique(Boutique boutique) {
		this.boutique = boutique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idboutiquier", nullable = false)
	public Boutiquier getBoutiquier() {
		return this.boutiquier;
	}

	public void setBoutiquier(Boutiquier boutiquier) {
		this.boutiquier = boutiquier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idclientv", nullable = false)
	public Clientvirtuel getClientvirtuel() {
		return this.clientvirtuel;
	}

	public void setClientvirtuel(Clientvirtuel clientvirtuel) {
		this.clientvirtuel = clientvirtuel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datecmp", length = 13)
	public Date getDatecmp() {
		return this.datecmp;
	}

	public void setDatecmp(Date datecmp) {
		this.datecmp = datecmp;
	}

}
