package model;
// Generated 14 juil. 2019 13:23:45 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Format generated by hbm2java
 */
@Entity
@Table(name = "format", schema = "public")
public class Format implements java.io.Serializable {

	private int idfromat;
	private Produitt produitt;
	private String typeformat;

	public Format() {
	}

	public Format(int idfromat, Produitt produitt) {
		this.idfromat = idfromat;
		this.produitt = produitt;
	}

	public Format(int idfromat, Produitt produitt, String typeformat) {
		this.idfromat = idfromat;
		this.produitt = produitt;
		this.typeformat = typeformat;
	}

	@Id

	@Column(name = "idfromat", unique = true, nullable = false)
	public int getIdfromat() {
		return this.idfromat;
	}

	public void setIdfromat(int idfromat) {
		this.idfromat = idfromat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idproduct", nullable = false)
	public Produitt getProduitt() {
		return this.produitt;
	}

	public void setProduitt(Produitt produitt) {
		this.produitt = produitt;
	}

	@Column(name = "typeformat", length = 254)
	public String getTypeformat() {
		return this.typeformat;
	}

	public void setTypeformat(String typeformat) {
		this.typeformat = typeformat;
	}

}
