package model;
// Generated 14 juil. 2019 13:23:45 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produitt generated by hbm2java
 */
@Entity
@Table(name = "produitt", schema = "public")
public class Produitt implements java.io.Serializable {

	private int idproduct;
	private Categorie categorie;
	private Stock stock;
	private String nom;
	private Set<Conditionnement> conditionnements = new HashSet<Conditionnement>(0);
	private Set<Depenses> depenseses = new HashSet<Depenses>(0);
	private Set<Detailscommande> detailscommandes = new HashSet<Detailscommande>(0);
	private Set<Format> formats = new HashSet<Format>(0);

	public Produitt() {
	}

	public Produitt(int idproduct, Categorie categorie, Stock stock) {
		this.idproduct = idproduct;
		this.categorie = categorie;
		this.stock = stock;
	}

	public Produitt(int idproduct, Categorie categorie, Stock stock, String nom, Set<Conditionnement> conditionnements,
			Set<Depenses> depenseses, Set<Detailscommande> detailscommandes, Set<Format> formats) {
		this.idproduct = idproduct;
		this.categorie = categorie;
		this.stock = stock;
		this.nom = nom;
		this.conditionnements = conditionnements;
		this.depenseses = depenseses;
		this.detailscommandes = detailscommandes;
		this.formats = formats;
	}

	@Id

	@Column(name = "idproduct", unique = true, nullable = false)
	public int getIdproduct() {
		return this.idproduct;
	}

	public void setIdproduct(int idproduct) {
		this.idproduct = idproduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcategorie", nullable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idstock", nullable = false)
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produitt")
	public Set<Conditionnement> getConditionnements() {
		return this.conditionnements;
	}

	public void setConditionnements(Set<Conditionnement> conditionnements) {
		this.conditionnements = conditionnements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produitt")
	public Set<Depenses> getDepenseses() {
		return this.depenseses;
	}

	public void setDepenseses(Set<Depenses> depenseses) {
		this.depenseses = depenseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produitt")
	public Set<Detailscommande> getDetailscommandes() {
		return this.detailscommandes;
	}

	public void setDetailscommandes(Set<Detailscommande> detailscommandes) {
		this.detailscommandes = detailscommandes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produitt")
	public Set<Format> getFormats() {
		return this.formats;
	}

	public void setFormats(Set<Format> formats) {
		this.formats = formats;
	}

}
