package model;
// Generated 14 juil. 2019 13:23:45 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quartier generated by hbm2java
 */
@Entity
@Table(name = "quartier", schema = "public")
public class Quartier implements java.io.Serializable {

	private int idquartier;
	private Departement departement;
	private String nom;
	private Set<Boutique> boutiques = new HashSet<Boutique>(0);

	public Quartier() {
	}

	public Quartier(int idquartier, Departement departement) {
		this.idquartier = idquartier;
		this.departement = departement;
	}

	public Quartier(int idquartier, Departement departement, String nom, Set<Boutique> boutiques) {
		this.idquartier = idquartier;
		this.departement = departement;
		this.nom = nom;
		this.boutiques = boutiques;
	}

	@Id

	@Column(name = "idquartier", unique = true, nullable = false)
	public int getIdquartier() {
		return this.idquartier;
	}

	public void setIdquartier(int idquartier) {
		this.idquartier = idquartier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddepartement", nullable = false)
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quartier")
	public Set<Boutique> getBoutiques() {
		return this.boutiques;
	}

	public void setBoutiques(Set<Boutique> boutiques) {
		this.boutiques = boutiques;
	}

}
