package model;
// Generated 14 juil. 2019 13:23:45 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", schema = "public")
public class Region implements java.io.Serializable {

	private int idregion;
	private Integer nom;
	private Set<Commune> communes = new HashSet<Commune>(0);

	public Region() {
	}

	public Region(int idregion) {
		this.idregion = idregion;
	}

	public Region(int idregion, Integer nom, Set<Commune> communes) {
		this.idregion = idregion;
		this.nom = nom;
		this.communes = communes;
	}

	@Id

	@Column(name = "idregion", unique = true, nullable = false)
	public int getIdregion() {
		return this.idregion;
	}

	public void setIdregion(int idregion) {
		this.idregion = idregion;
	}

	@Column(name = "nom")
	public Integer getNom() {
		return this.nom;
	}

	public void setNom(Integer nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Commune> getCommunes() {
		return this.communes;
	}

	public void setCommunes(Set<Commune> communes) {
		this.communes = communes;
	}

}
